### ISSUE TITLE
I just installed and enabled this module and it's parent but no new field types created

### ISSUE THREAD

**Issue by slabo** [drupal-media/media_entity_embeddable_video#4]
Hello.

I was looking for solutions to display uploaded videos and came across this module. Installed media_entity first then enabled it and installed media_entity_embeddable_video and enabled that as well. 

In the administration menu, I go to add a new field to a content type but there are no new media type fields. Am I missing something?

Any help appreciated, 
thanks.

**Comment by slabo** [comment]
Ok, I just saw something I missed. 

_In order to provide integration for a new video source you need to implement a video provider plugin. See \Drupal\media_entity_embeddable_video\Plugin\MediaEntity\VideoProvider for examples._

It should be **modules/media_entity_embeddable_video/src/Plugin/MediaEntity/VideoProvider**

just missed **src** from path. I should get more sleep or more coffee.

**Comment by slabo** [comment]
Newb here. What do I do with this any of these files ??

Aol.php
AolPlaylist.php
GrabNetworks.php
Wochit.php
YouTube.php

**Comment by slabo** [comment]
sorry, Newb here. What do I do with this any of these files ??

Aol.php
AolPlaylist.php
GrabNetworks.php
Wochit.php
YouTube.php

**Comment by slashrsm** [comment]
This plugin provide integration with video services. In order to use them create media bundle with texarea field for embed code and configure bundle to use that field as video source. Media bundle UI should be pretty self explanatory.
