### ISSUE TITLE
Validation of youtube urls (and others) fails because of constraint validation checks wrong value

### ISSUE THREAD

**Issue by pixelmord** [drupal-media/media_entity_embeddable_video#9]
See: https://www.drupal.org/node/2578947#comment-10505140

PR created

**Comment by pixelmord** [comment]
https://github.com/drupal-media/media_entity_embeddable_video/pull/10

**Comment by slashrsm** [comment]
Was solved by https://github.com/drupal-media/media_entity_embeddable_video/commit/2199a193100f60d69e1fd419d6820d10cade5b22
